project:
  type: website
  output-dir: .

website:
  navbar:
    left:
      - text: About Me
        href: about.qmd
      - text: CV
        href: cv.qmd
      - text: Contact
        href: contact.qmd
format:
  html:
    theme: cosmo
    toc: true
